export const nodeGlobals = {
    Buffer,
    __dirname,
    __filename,
    clearImmediate,
    clearInterval,
    clearTimeout,
    console,
    exports,
    global,
    module,
    process,
    queueMicrotask,
    require,
    setImmediate,
    setInterval,
    setTimeout,
};
